version: '3.6'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
    - "6379:6379"
  myservice:
    build: .
    image: myservice
    environment:
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    restart: unless-stopped
